addpath('/home/ubuntu', '-begin');
report = prototype_multiscale_wfb_pdfb_coordinates( ...
    'ToolboxPath', '/opt/ctsteg/toolboxes/contourlet-real', ...
    'OutputPath', ...
        '/srv/ctsteg/evidence/pdfb-multiscale-wfb-prototype.json');
disp(jsonencode(report.gates));
