function summary = run_pair(coverPath, secretPath, outputDirectory, options)
%RUN_PAIR Execute one MATLAB/Contourlet Toolbox cover-secret experiment.

arguments
    coverPath (1,1) string
    secretPath (1,1) string
    outputDirectory (1,1) string
    options.Alpha (1,1) double {mustBePositive} = 0.15
    options.PFilter (1,1) string = "9-7"
    options.DFilter (1,1) string = "pkva"
    options.NLevels (1,:) double = [2 2 2 2]
    options.BandPolicy (1,1) string ...
        {mustBeMember(options.BandPolicy, ["finest","all_details"])} = "finest"
    options.EmbedLowpass (1,1) logical = false
    options.QuantizeStego (1,1) logical = true
end

cover = im2double(imresize(im2gray(imread(coverPath)), [512 512])) * 255;
secret = im2double(imresize(im2gray(imread(secretPath)), [512 512])) * 255;
[stego, encrypted, metadata] = embed_pdfb(cover, secret, ...
    Alpha=options.Alpha, ...
    PFilter=options.PFilter, ...
    DFilter=options.DFilter, ...
    NLevels=options.NLevels, ...
    BandPolicy=options.BandPolicy, ...
    EmbedLowpass=options.EmbedLowpass, ...
    QuantizeStego=options.QuantizeStego);
[recovered, extractedEncrypted] = extract_pdfb(stego, cover, ...
    Alpha=options.Alpha, ...
    PFilter=options.PFilter, ...
    DFilter=options.DFilter, ...
    NLevels=options.NLevels, ...
    BandPolicy=options.BandPolicy, ...
    EmbedLowpass=options.EmbedLowpass);

if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
imwrite(uint8(min(max(round(cover), 0), 255)), ...
    fullfile(outputDirectory, "cover.png"));
imwrite(uint8(min(max(round(secret), 0), 255)), ...
    fullfile(outputDirectory, "secret.png"));
imwrite(uint8(min(max(round(encrypted), 0), 255)), ...
    fullfile(outputDirectory, "encrypted_secret.png"));
imwrite(uint8(min(max(round(stego), 0), 255)), ...
    fullfile(outputDirectory, "stego.png"));
imwrite(uint8(min(max(round(extractedEncrypted), 0), 255)), ...
    fullfile(outputDirectory, "extracted_encrypted.png"));
imwrite(uint8(min(max(round(recovered), 0), 255)), ...
    fullfile(outputDirectory, "recovered_secret.png"));

mseStego = mean((cover - stego).^2, "all");
psnrStego = 10 * log10(255^2 / mseStego);
secretBytes = uint8(min(max(round(secret), 0), 255));
recoveredBytes = uint8(min(max(round(recovered), 0), 255));
xorValues = bitxor(secretBytes, recoveredBytes);
differingBits = sum(arrayfun(@(value) sum(dec2bin(value,8) == "1"), ...
    xorValues(:)));
ber = differingBits / (numel(secretBytes) * 8);

summary = struct( ...
    "metadata", metadata, ...
    "psnr_db", psnrStego, ...
    "ssim", ssim(uint8(stego), uint8(cover)), ...
    "ber", ber);
fid = fopen(fullfile(outputDirectory, "metrics.json"), "w");
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", jsonencode(summary, PrettyPrint=true));
end

