function records = sweep_pdfb_stage0_profiles(varargin)
%SWEEP_PDFB_STAGE0_PROFILES Diagnose explicit PDFB filter/level candidates.
%
% This is an exploratory Stage-0 sweep, not final gate evidence.  It uses
% one deterministic probe per directional band and does not relax any of
% the final thresholds.

parser = inputParser;
addParameter(parser, 'ToolboxPath', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'OutputPath', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'PFilters', {'9-7', '5-3', 'Burt', 'pkva'}, @iscell);
addParameter(parser, 'DFilters', ...
    {'haar', '5-3', '9-7', 'pkva6', 'pkva8', 'pkva12', 'pkva'}, @iscell);
addParameter(parser, 'NLevels', [2 2 2 2], ...
    @(x) isnumeric(x) && isvector(x) && ~isempty(x));
addParameter(parser, 'CoverSize', 512, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(parser, 'RequiredSlots', 222360, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
addParameter(parser, 'ProbeDelta', 1.0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
parse(parser, varargin{:});
options = parser.Results;

toolboxPath = char(options.ToolboxPath);
outputPath = char(options.OutputPath);
assert(isfolder(toolboxPath), 'PDFB:SweepToolboxMissing', ...
    'Contourlet Toolbox directory does not exist: %s', toolboxPath);
assert(~isempty(outputPath), 'PDFB:SweepOutputMissing', ...
    'OutputPath must be supplied.');
assert(~isfile(outputPath), 'PDFB:SweepOutputExists', ...
    'Refusing to overwrite existing sweep output: %s', outputPath);
addpath(genpath(toolboxPath), '-begin');

nlevels = double(options.NLevels(:).');
coverSize = double(options.CoverSize);
requiredSlots = double(options.RequiredSlots);
probeDelta = double(options.ProbeDelta);
assert(coverSize == 512, 'PDFB:SweepCoverSize', ...
    'The diagnostic sweep requires CoverSize=512.');
assert(isequal(nlevels, [2 2 2 2]), 'PDFB:SweepNLevels', ...
    'The diagnostic sweep requires NLevels=[2 2 2 2].');

[rows, columns] = ndgrid(uint32(0:coverSize - 1), ...
    uint32(0:coverSize - 1));
imageUint8 = uint8(mod( ...
    rows .* uint32(37) + columns .* uint32(19) + ...
    mod(rows .* columns, uint32(251)), ...
    uint32(256)));
image = double(imageUint8);

records = struct( ...
    'pfilter', {}, ...
    'dfilter', {}, ...
    'eligible_level', {}, ...
    'directional_bands', {}, ...
    'candidate_coefficients', {}, ...
    'reconstruction_max_abs_error', {}, ...
    'minimum_self_gain', {}, ...
    'maximum_cross_talk', {}, ...
    'maximum_off_target_l2_ratio', {}, ...
    'capacity_passed', {}, ...
    'reconstruction_passed', {}, ...
    'self_gain_passed', {}, ...
    'cross_talk_passed', {}, ...
    'off_target_passed', {}, ...
    'all_numeric_thresholds_passed', {}, ...
    'error_identifier', {}, ...
    'error_message', {});

for pfilterIndex = 1:numel(options.PFilters)
    pfilter = char(options.PFilters{pfilterIndex});
    for dfilterIndex = 1:numel(options.DFilters)
        dfilter = char(options.DFilters{dfilterIndex});
        try
            coefficients = pdfbdec(image, pfilter, dfilter, nlevels);
            baselineImage = pdfbrec(coefficients, pfilter, dfilter);
            reconstructionDifference = double(baselineImage) - image;
            reconstructionMaxAbsError = ...
                max(abs(reconstructionDifference(:)));
            baselineRoundTrip = pdfbdec( ...
                baselineImage, pfilter, dfilter, nlevels);
            for eligibleLevel = 1:numel(nlevels)
                eligibleCellIndex = eligibleLevel + 1;
                eligible = coefficients{eligibleCellIndex};
                baselineEligible = baselineRoundTrip{eligibleCellIndex};
                [minimumSelfGain, maximumCrossTalk, ...
                    maximumOffTargetL2Ratio] = probe_level( ...
                    coefficients, baselineEligible, eligibleCellIndex, ...
                    pfilter, dfilter, nlevels, probeDelta);
                candidateCoefficients = sum(cellfun(@numel, eligible));
                record = base_record(pfilter, dfilter, eligibleLevel);
                record.directional_bands = numel(eligible);
                record.candidate_coefficients = candidateCoefficients;
                record.reconstruction_max_abs_error = ...
                    reconstructionMaxAbsError;
                record.minimum_self_gain = minimumSelfGain;
                record.maximum_cross_talk = maximumCrossTalk;
                record.maximum_off_target_l2_ratio = ...
                    maximumOffTargetL2Ratio;
                record.capacity_passed = ...
                    candidateCoefficients >= requiredSlots;
                record.reconstruction_passed = ...
                    reconstructionMaxAbsError <= 1e-8;
                record.self_gain_passed = minimumSelfGain >= 0.99;
                record.cross_talk_passed = maximumCrossTalk <= 0.01;
                record.off_target_passed = ...
                    maximumOffTargetL2Ratio <= 0.05;
                record.all_numeric_thresholds_passed = ...
                    record.capacity_passed && ...
                    record.reconstruction_passed && ...
                    record.self_gain_passed && ...
                    record.cross_talk_passed && ...
                    record.off_target_passed;
                records(end + 1) = record; %#ok<AGROW>
            end
        catch errorRecord
            record = base_record(pfilter, dfilter, 0);
            record.error_identifier = errorRecord.identifier;
            record.error_message = errorRecord.message;
            records(end + 1) = record; %#ok<AGROW>
        end
    end
end

outputDirectory = fileparts(outputPath);
if ~isempty(outputDirectory) && ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
write_csv(outputPath, records);
end


function [minimumSelfGain, maximumCrossTalk, ...
    maximumOffTargetL2Ratio] = probe_level( ...
        coefficients, baselineEligible, eligibleCellIndex, ...
        pfilter, dfilter, nlevels, probeDelta)
eligible = coefficients{eligibleCellIndex};
selfGains = zeros(1, numel(eligible));
crossTalk = zeros(1, numel(eligible));
offTarget = zeros(1, numel(eligible));
for bandIndex = 1:numel(eligible)
    band = eligible{bandIndex};
    row = 1 + floor(0.5 * (size(band, 1) - 1));
    column = 1 + floor(0.5 * (size(band, 2) - 1));
    modified = coefficients;
    modified{eligibleCellIndex}{bandIndex}(row, column) = ...
        modified{eligibleCellIndex}{bandIndex}(row, column) + probeDelta;
    modifiedImage = pdfbrec(modified, pfilter, dfilter);
    roundTrip = pdfbdec(modifiedImage, pfilter, dfilter, nlevels);
    roundTripEligible = roundTrip{eligibleCellIndex};
    selfGains(bandIndex) = ...
        (double(roundTripEligible{bandIndex}(row, column)) - ...
        double(baselineEligible{bandIndex}(row, column))) / probeDelta;
    offTargetSquared = 0.0;
    for otherBandIndex = 1:numel(roundTripEligible)
        deltaBand = double(roundTripEligible{otherBandIndex}) - ...
            double(baselineEligible{otherBandIndex});
        if otherBandIndex == bandIndex
            deltaBand(row, column) = 0.0;
        end
        crossTalk(bandIndex) = max( ...
            crossTalk(bandIndex), ...
            max(abs(deltaBand(:))) / abs(probeDelta));
        offTargetSquared = offTargetSquared + sum(deltaBand(:) .^ 2);
    end
    offTarget(bandIndex) = sqrt(offTargetSquared) / abs(probeDelta);
end
minimumSelfGain = min(selfGains);
maximumCrossTalk = max(crossTalk);
maximumOffTargetL2Ratio = max(offTarget);
end


function record = base_record(pfilter, dfilter, eligibleLevel)
record = struct();
record.pfilter = pfilter;
record.dfilter = dfilter;
record.eligible_level = eligibleLevel;
record.directional_bands = 0;
record.candidate_coefficients = 0;
record.reconstruction_max_abs_error = NaN;
record.minimum_self_gain = NaN;
record.maximum_cross_talk = NaN;
record.maximum_off_target_l2_ratio = NaN;
record.capacity_passed = false;
record.reconstruction_passed = false;
record.self_gain_passed = false;
record.cross_talk_passed = false;
record.off_target_passed = false;
record.all_numeric_thresholds_passed = false;
record.error_identifier = '';
record.error_message = '';
end


function write_csv(outputPath, records)
fileIdentifier = fopen(outputPath, 'w');
assert(fileIdentifier >= 0, 'PDFB:SweepOutputOpen', ...
    'Could not open sweep output: %s', outputPath);
cleanup = onCleanup(@() fclose(fileIdentifier)); %#ok<NASGU>
fprintf(fileIdentifier, [ ...
    'pfilter,dfilter,eligible_level,directional_bands,' ...
    'candidate_coefficients,reconstruction_max_abs_error,' ...
    'minimum_self_gain,maximum_cross_talk,' ...
    'maximum_off_target_l2_ratio,capacity_passed,' ...
    'reconstruction_passed,self_gain_passed,cross_talk_passed,' ...
    'off_target_passed,all_numeric_thresholds_passed,' ...
    'error_identifier,error_message\n']);
for index = 1:numel(records)
    record = records(index);
    fprintf(fileIdentifier, ...
        ['%s,%s,%d,%d,%d,%.17g,%.17g,%.17g,%.17g,' ...
        '%d,%d,%d,%d,%d,%d,%s,%s\n'], ...
        csv_escape(record.pfilter), ...
        csv_escape(record.dfilter), ...
        record.eligible_level, ...
        record.directional_bands, ...
        record.candidate_coefficients, ...
        record.reconstruction_max_abs_error, ...
        record.minimum_self_gain, ...
        record.maximum_cross_talk, ...
        record.maximum_off_target_l2_ratio, ...
        record.capacity_passed, ...
        record.reconstruction_passed, ...
        record.self_gain_passed, ...
        record.cross_talk_passed, ...
        record.off_target_passed, ...
        record.all_numeric_thresholds_passed, ...
        csv_escape(record.error_identifier), ...
        csv_escape(record.error_message));
end
end


function value = csv_escape(input)
value = char(input);
value = strrep(value, '"', '""');
if any(value == ',') || any(value == '"') || ...
        any(value == newline) || any(value == sprintf('\r'))
    value = ['"' value '"'];
end
end
