function report = explore_pdfb_multiscale_coordinates_20260730(varargin)
%EXPLORE_PDFB_MULTISCALE_COORDINATES_20260730
% Explore an independent coordinate system inside the locked PDFB range.
%
% The raw fourth-level directional arrays contain 262,144 numbers but the
% Laplacian-pyramid residual at that level has only 196,608 independent
% degrees of freedom.  This script parameterizes the valid residual with the
% three high-pass outputs of the same 9-7 critical wavelet bank used by the
% toolbox.  It does this at P4 and P3, then maps each valid residual through
% the locked pkva directional bank.  The resulting six virtual bands contain
% 245,760 independent coordinates, enough for the fixed 222,360-bit payload.
%
% This is exploratory evidence, not the locked Stage-0 artifact.  It does not
% change or relax the numerical thresholds.

parser = inputParser;
addParameter(parser, 'ToolboxPath', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'OutputPath', '', @(x) ischar(x) || isstring(x));
addParameter(parser, 'ProbeDelta', 1.0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(parser, 'RequiredSlots', 222360, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x));
parse(parser, varargin{:});
options = parser.Results;

toolboxPath = canonical_path(char(options.ToolboxPath));
outputPath = char(options.OutputPath);
probeDelta = double(options.ProbeDelta);
requiredSlots = double(options.RequiredSlots);
assert(isfolder(toolboxPath), 'PDFBVirtual:ToolboxMissing', ...
    'Contourlet Toolbox directory does not exist: %s', toolboxPath);
assert(requiredSlots == 222360, 'PDFBVirtual:RequiredSlots', ...
    'The exploratory audit requires exactly 222360 slots.');
if ~isempty(outputPath)
    assert(~isfile(outputPath), 'PDFBVirtual:OutputExists', ...
        'Refusing to overwrite existing output: %s', outputPath);
end

addpath(genpath(toolboxPath), '-begin');
assert(~isempty(which('pdfbdec')) && ~isempty(which('pdfbrec')), ...
    'PDFBVirtual:MissingPDFB', 'pdfbdec/pdfbrec are unavailable.');
assert(~isempty(which('wfb2dec')) && ~isempty(which('wfb2rec')), ...
    'PDFBVirtual:MissingWFB', 'wfb2dec/wfb2rec are unavailable.');
assert(~isempty(which('dfbdec_l')) && ~isempty(which('dfbrec_l')), ...
    'PDFBVirtual:MissingDFB', 'dfbdec_l/dfbrec_l are unavailable.');

pfilter = '9-7';
dfilter = 'pkva';
nlevels = [2 2 2 2];
[h, g] = pfilters(pfilter);

coverSize = 512;
[rows, columns] = ndgrid(uint32(0:coverSize - 1), ...
    uint32(0:coverSize - 1));
imageUint8 = uint8(mod( ...
    rows .* uint32(37) + columns .* uint32(19) + ...
    mod(rows .* columns, uint32(251)), ...
    uint32(256)));
image = double(imageUint8);

coefficients = pdfbdec(image, pfilter, dfilter, nlevels);
reconstructed = pdfbrec(coefficients, pfilter, dfilter);
reconstructionDifference = double(reconstructed) - image;

[baselineVirtual, baselineLeakage] = decode_virtual( ...
    coefficients, h, g, dfilter);
assert(numel(baselineVirtual) == 6, 'PDFBVirtual:BandCount', ...
    'Expected six multiscale virtual bands.');
virtualBandIds = { ...
    'V:P4:LH', 'V:P4:HL', 'V:P4:HH', ...
    'V:P3:LH', 'V:P3:HL', 'V:P3:HH'};
virtualCounts = cellfun(@numel, baselineVirtual);
assert(isequal(virtualCounts, ...
    [65536 65536 65536 16384 16384 16384]), ...
    'PDFBVirtual:BandShapes', ...
    'Unexpected multiscale virtual-coordinate shapes.');
candidateCoordinates = sum(virtualCounts);
assert(candidateCoordinates == 245760, 'PDFBVirtual:Capacity', ...
    'Expected exactly 245760 independent P3+P4 coordinates.');
assert(candidateCoordinates >= requiredSlots, ...
    'PDFBVirtual:Capacity', 'Virtual coordinate pool is too small.');

baselineEncoded = encode_virtual( ...
    coefficients, baselineVirtual, h, g, dfilter);
baselineImage = pdfbrec(baselineEncoded, pfilter, dfilter);
baselineRoundTrip = pdfbdec( ...
    baselineImage, pfilter, dfilter, nlevels);
[baselineReadback, baselineReadbackLeakage] = decode_virtual( ...
    baselineRoundTrip, h, g, dfilter);

probeFractions = [0.25 0.5 0.75];
probes = struct( ...
    'band_id', {}, ...
    'row', {}, ...
    'column', {}, ...
    'fraction', {}, ...
    'self_gain', {}, ...
    'maximum_cross_talk', {}, ...
    'off_target_l2_ratio', {});
for bandIndex = 1:numel(baselineVirtual)
    band = baselineVirtual{bandIndex};
    for fractionIndex = 1:numel(probeFractions)
        fraction = probeFractions(fractionIndex);
        row = 1 + floor(fraction * (size(band, 1) - 1));
        column = 1 + floor(fraction * (size(band, 2) - 1));
        modifiedVirtual = copy_cells(baselineVirtual);
        modifiedVirtual{bandIndex}(row, column) = ...
            modifiedVirtual{bandIndex}(row, column) + probeDelta;
        modifiedCoefficients = encode_virtual( ...
            coefficients, modifiedVirtual, h, g, dfilter);
        modifiedImage = pdfbrec( ...
            modifiedCoefficients, pfilter, dfilter);
        roundTrip = pdfbdec( ...
            modifiedImage, pfilter, dfilter, nlevels);
        [readback, ~] = decode_virtual(roundTrip, h, g, dfilter);

        targetDelta = ...
            double(readback{bandIndex}(row, column)) - ...
            double(baselineReadback{bandIndex}(row, column));
        maximumCrossTalk = 0.0;
        offTargetSquared = 0.0;
        for otherBandIndex = 1:numel(readback)
            deltaBand = double(readback{otherBandIndex}) - ...
                double(baselineReadback{otherBandIndex});
            if otherBandIndex == bandIndex
                deltaBand(row, column) = 0.0;
            end
            maximumCrossTalk = max( ...
                maximumCrossTalk, max(abs(deltaBand(:))) / probeDelta);
            offTargetSquared = offTargetSquared + ...
                sum(deltaBand(:) .^ 2);
        end

        probe = struct();
        probe.band_id = virtualBandIds{bandIndex};
        probe.row = row - 1;
        probe.column = column - 1;
        probe.fraction = fraction;
        probe.self_gain = targetDelta / probeDelta;
        probe.maximum_cross_talk = maximumCrossTalk;
        probe.off_target_l2_ratio = sqrt(offTargetSquared) / probeDelta;
        probes(end + 1) = probe; %#ok<AGROW>
    end
end

% Dense, exact-format trial.  All P4 coordinates are used, followed by an
% equal 8,584-coordinate prefix from each P3 virtual band:
% 196,608 + 3*8,584 = 222,360.
denseVirtual = copy_cells(baselineVirtual);
denseMasks = cellfun(@(band) false(size(band)), ...
    baselineVirtual, 'UniformOutput', false);
denseSigns = cellfun(@(band) zeros(size(band)), ...
    baselineVirtual, 'UniformOutput', false);
for bandIndex = 1:3
    denseMasks{bandIndex}(:) = true;
end
for bandIndex = 4:6
    denseMasks{bandIndex}(1:8584) = true;
end
denseSequence = 0;
for bandIndex = 1:numel(denseVirtual)
    selected = find(denseMasks{bandIndex});
    sequence = denseSequence + (1:numel(selected)).';
    signs = 2.0 * double(mod(sequence .* 1103515245 + 12345, 2)) - 1.0;
    denseSigns{bandIndex}(selected) = signs;
    denseVirtual{bandIndex}(selected) = ...
        denseVirtual{bandIndex}(selected) + probeDelta * signs;
    denseSequence = denseSequence + numel(selected);
end
assert(denseSequence == requiredSlots, 'PDFBVirtual:DenseSlotCount', ...
    'Dense trial does not contain exactly 222360 selected coordinates.');
denseCoefficients = encode_virtual( ...
    coefficients, denseVirtual, h, g, dfilter);
denseImage = pdfbrec(denseCoefficients, pfilter, dfilter);
denseRoundTrip = pdfbdec(denseImage, pfilter, dfilter, nlevels);
[denseReadback, denseReadbackLeakage] = decode_virtual( ...
    denseRoundTrip, h, g, dfilter);
denseMaximumAbsoluteError = 0.0;
denseSquaredError = 0.0;
denseSignErrors = 0;
denseOffTargetSquared = 0.0;
for bandIndex = 1:numel(denseReadback)
    deltaBand = double(denseReadback{bandIndex}) - ...
        double(baselineReadback{bandIndex});
    targetBand = probeDelta * denseSigns{bandIndex};
    selected = denseMasks{bandIndex};
    errors = deltaBand(selected) - targetBand(selected);
    denseMaximumAbsoluteError = max( ...
        denseMaximumAbsoluteError, max(abs(errors(:))));
    denseSquaredError = denseSquaredError + sum(errors(:) .^ 2);
    denseSignErrors = denseSignErrors + sum( ...
        sign_with_positive_zero(deltaBand(selected)) ~= ...
        sign_with_positive_zero(targetBand(selected)));
    unselected = ~selected;
    denseOffTargetSquared = denseOffTargetSquared + ...
        sum(deltaBand(unselected) .^ 2);
end

minimumSelfGain = min([probes.self_gain]);
maximumCrossTalk = max([probes.maximum_cross_talk]);
maximumOffTargetL2Ratio = max([probes.off_target_l2_ratio]);

report = struct();
report.schema = 1;
report.exploratory = true;
report.scheme = ...
    'pdfb_9_7_pkva_multiscale_range_coordinates_p3_p4_v1';
report.claim_boundary = [ ...
    'Independent PDFB-range coordinates, not raw directional-array ' ...
    'coefficients and not author-equivalent settings.'];
report.parameters = struct( ...
    'pfilter', pfilter, ...
    'dfilter', dfilter, ...
    'nlevels', nlevels, ...
    'eligible_pyramid_levels_from_coarse', [3 4], ...
    'required_slots', requiredSlots, ...
    'probe_delta', probeDelta, ...
    'probe_fractions', probeFractions);
report.rank_certificate = struct( ...
    'p4_independent_coordinates', 196608, ...
    'p3_independent_coordinates', 49152, ...
    'p3_p4_independent_coordinates', candidateCoordinates, ...
    'unused_coordinates', candidateCoordinates - requiredSlots, ...
    'candidate_utilization', requiredSlots / candidateCoordinates, ...
    'construction', ...
    'three critical 9-7 highpass coordinates per 2x2 block per level');
report.virtual_bands = band_records(virtualBandIds, baselineVirtual);
report.perfect_reconstruction = struct( ...
    'max_abs_error', max(abs(reconstructionDifference(:))), ...
    'rmse', sqrt(mean(reconstructionDifference(:) .^ 2)));
report.valid_range_leakage = struct( ...
    'baseline_p4_lowpass_max_abs', baselineLeakage(1), ...
    'baseline_p3_lowpass_max_abs', baselineLeakage(2), ...
    'baseline_readback_p4_lowpass_max_abs', ...
        baselineReadbackLeakage(1), ...
    'baseline_readback_p3_lowpass_max_abs', ...
        baselineReadbackLeakage(2), ...
    'dense_readback_p4_lowpass_max_abs', denseReadbackLeakage(1), ...
    'dense_readback_p3_lowpass_max_abs', denseReadbackLeakage(2));
report.independent_writability = struct( ...
    'coordinate_semantics', ...
        'decoded virtual coordinates after locked PDFB synthesize/reanalyze', ...
    'probe_count', numel(probes), ...
    'minimum_self_gain', minimumSelfGain, ...
    'maximum_cross_talk', maximumCrossTalk, ...
    'maximum_off_target_l2_ratio', maximumOffTargetL2Ratio, ...
    'probes', probes);
report.dense_222360_sign_trial = struct( ...
    'slot_count', denseSequence, ...
    'sign_errors', denseSignErrors, ...
    'maximum_absolute_coordinate_error', denseMaximumAbsoluteError, ...
    'selected_l2_error_ratio', ...
        sqrt(denseSquaredError) / (probeDelta * sqrt(requiredSlots)), ...
    'unselected_l2_ratio', ...
        sqrt(denseOffTargetSquared) / (probeDelta * sqrt(requiredSlots)));
report.locked_thresholds = struct( ...
    'reconstruction_max_abs', 1e-8, ...
    'minimum_self_gain', 0.99, ...
    'maximum_cross_talk', 0.01, ...
    'maximum_off_target_l2_ratio', 0.05, ...
    'minimum_probes_per_band', 3, ...
    'required_slots', requiredSlots);
report.passed = ...
    report.perfect_reconstruction.max_abs_error <= 1e-8 && ...
    candidateCoordinates >= requiredSlots && ...
    numel(probes) >= 3 * numel(baselineVirtual) && ...
    minimumSelfGain >= 0.99 && ...
    maximumCrossTalk <= 0.01 && ...
    maximumOffTargetL2Ratio <= 0.05 && ...
    denseSignErrors == 0;

fprintf( ...
    ['virtual_capacity=%d required=%d self=%.17g cross=%.17g ' ...
     'off_l2=%.17g dense_sign_errors=%d dense_max_error=%.17g ' ...
     'passed=%d\n'], ...
    candidateCoordinates, requiredSlots, minimumSelfGain, ...
    maximumCrossTalk, maximumOffTargetL2Ratio, denseSignErrors, ...
    denseMaximumAbsoluteError, report.passed);

if ~isempty(outputPath)
    outputDirectory = fileparts(outputPath);
    if ~isempty(outputDirectory) && ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end
    fileIdentifier = fopen(outputPath, 'w');
    assert(fileIdentifier >= 0, 'PDFBVirtual:OutputOpen', ...
        'Could not open output: %s', outputPath);
    cleanup = onCleanup(@() fclose(fileIdentifier)); %#ok<NASGU>
    fwrite(fileIdentifier, jsonencode(report), 'char');
    fwrite(fileIdentifier, newline, 'char');
end
end


function [virtual, leakage] = decode_virtual(coefficients, h, g, dfilter)
assert(iscell(coefficients) && numel(coefficients) == 5, ...
    'PDFBVirtual:CoefficientStructure', ...
    'Expected the locked five-cell PDFB structure.');
detailP4 = dfbrec_l(coefficients{5}, dfilter);
[lowP4, p4LH, p4HL, p4HH] = wfb2dec(detailP4, h, g);
detailP3 = dfbrec_l(coefficients{4}, dfilter);
[lowP3, p3LH, p3HL, p3HH] = wfb2dec(detailP3, h, g);
virtual = {p4LH, p4HL, p4HH, p3LH, p3HL, p3HH};
leakage = [max(abs(lowP4(:))) max(abs(lowP3(:)))];
end


function output = encode_virtual( ...
        baselineCoefficients, virtual, h, g, dfilter)
assert(numel(virtual) == 6, 'PDFBVirtual:BandCount', ...
    'Expected six virtual bands.');
output = baselineCoefficients;
detailP4 = wfb2rec( ...
    zeros(size(virtual{1})), ...
    virtual{1}, virtual{2}, virtual{3}, h, g);
detailP3 = wfb2rec( ...
    zeros(size(virtual{4})), ...
    virtual{4}, virtual{5}, virtual{6}, h, g);
output{5} = dfbdec_l(detailP4, dfilter, 2);
output{4} = dfbdec_l(detailP3, dfilter, 2);
end


function output = copy_cells(input)
output = cell(size(input));
for index = 1:numel(input)
    output{index} = input{index};
end
end


function output = sign_with_positive_zero(input)
output = ones(size(input));
output(input < 0) = -1;
end


function records = band_records(identifiers, bands)
records = struct( ...
    'band_id', {}, 'shape', {}, 'coordinate_count', {});
for index = 1:numel(bands)
    record = struct();
    record.band_id = identifiers{index};
    record.shape = [size(bands{index}, 1) size(bands{index}, 2)];
    record.coordinate_count = numel(bands{index});
    records(end + 1) = record; %#ok<AGROW>
end
end


function output = canonical_path(input)
if exist('OCTAVE_VERSION', 'builtin') ~= 0
    output = canonicalize_file_name(input);
    if isempty(output)
        output = input;
    end
else
    file = javaObject('java.io.File', char(input));
    output = char(file.getCanonicalPath());
end
end
